apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-config
data:
  app.ini: |
    APP_NAME = {{ .Values.configMap.APP_NAME }}
    [database]
    DB_TYPE = {{ .Values.configMap.DB_TYPE }}
    HOST = {{ .Values.postgres.host }}:{{ .Values.postgres.port }}
    NAME = {{ .Values.postgres.database }}
    USER = {{ .Values.postgres.user }}
    PASSWD = {{ .Values.postgres.password }}