---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: {{ .Release.Namespace | default .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "gitea")) | nindent 2 }}
  annotations:
    kubernetes.io/ingress.class: {{ include "helm_lib_module_ingress_class" . | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    {{- if .Values.gitea.ingress.annotations }}
    {{- toYaml .Values.gitea.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ include "helm_lib_module_ingress_class" . | quote }}
  rules:
  - host: {{ include "helm_lib_module_public_domain" (list . "gitea") }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea
            port:
              number: 80
  {{- if .Values.gitea.ssh.enabled }}
  - host: {{ include "helm_lib_module_public_domain" (list . "gitea-ssh") }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea
            port:
              number: 22
  {{- end }}
  {{- if (include "helm_lib_module_https_ingress_tls_enabled" .) }}
  tls:
    - hosts:
        - {{ include "helm_lib_module_public_domain" (list . "gitea") }}
        {{- if .Values.gitea.ssh.enabled }}
        - {{ include "helm_lib_module_public_domain" (list . "gitea-ssh") }}
        {{- end }}
      secretName: {{ include "helm_lib_module_https_secret_name" (list . "gitea-tls") }}
  {{- end }}