---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | default .Chart.Name }}
  labels:
    {{- include "helm_lib_module_labels" (list . (dict "app" "gitea")) | nindent 4 }}
    {{- if .Values.namespace.labels }}
    {{- toYaml .Values.namespace.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.namespace.annotations }}
    {{- toYaml .Values.namespace.annotations | nindent 4 }}
    {{- end }}
    deckhouse.io/module: "{{ .Chart.Name }}"
    deckhouse.io/version: "{{ .Chart.Version }}"