apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: gitea
        - name: POSTGRES_USER
          value: gitea
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-postgresql-password
              key: postgresql-password
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-postgresql
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgresql-password
type: Opaque
data:
  postgresql-password: bXlzZWNyZXRwYXNzd29yZA==